[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "napi_lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[dependencies]
napi = { version = "2.16.4", features = ["serde-json"] }
napi-derive = "2.16.3"

[build-dependencies]
napi-build = "2.1.3"
